FROM php:8.4-cli-alpine
RUN apk add --no-cache postgresql-dev && \
    docker-php-ext-install pdo_pgsql pgsql && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
WORKDIR /var/www/html
COPY ../backend .
RUN composer install --no-interaction --optimize-autoloader
EXPOSE 8000
CMD php artisan serve --host=0.0.0.0 --port=8000
