FROM php:8.4-cli-alpine
RUN apk add --no-cache curl && \
    docker-php-ext-install pdo_mysql mysqli && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
WORKDIR /var/www/html
COPY ../backend .
EXPOSE 8000
CMD composer install --no-interaction --optimize-autoloader && php artisan serve --host=0.0.0.0 --port=8000
